[project]
name = "seamstress"
version = "1.1.0"
authors = [
    { name="Peter Thomas" }
]
description = "A utility for testing concurrent code."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["threading", "multiprocessing", "locks", "testing"]

[project.urls]
Homepage = "https://github.com/panthas05/seamstress"
Issues = "https://github.com/panthas05/seamstress/issues"
Repository = "https://github.com/panthas05/seamstress"

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"

[tool.mypy]
strict = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "CPY001",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D200",
    "D401",
    "D203",
    "D205",
    "D212",
    "E501",
    "FIX002",
    "N818",
    "PT009",
    "PT027",
    "SIM117",
    "TD002",
    "TD003",
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "prek>=0.3.6",
    "ruff>=0.16.5",
]
