[project]
name = "seamstress"
version = "1.1.0"
authors = [
    { name="Peter Thomas" }
]
description = "A utility for testing concurrent code."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
keywords = ["threading", "multiprocessing", "locks", "testing"]

[project.urls]
Homepage = "https://github.com/panthas05/seamstress"
Issues = "https://github.com/panthas05/seamstress/issues"
Repository = "https://github.com/panthas05/seamstress"

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"

[tool.mypy]
strict = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D100",  # TODO: remove
    "D101",  # TODO: remove
    "D102",  # TODO: remove
    "D103",  # TODO: remove
    "D104",  # TODO: remove
    "D105",  # TODO: maybe remove
    "D107",  # TODO: maybe remove
    "D200",  # TODO: remove
    "D401",  # TODO: remove
    "D400",  # TODO: remove
    "D415",  # TODO: remove
    "D203",
    "D205",  # TODO: maybe remove
    "D212",
    "E501",  # TODO: maybe remove
    "EM101",  # TODO: maybe remove
    "EM102",  # TODO: maybe remove
    "FIX002",
    "N818",
    "PT009",
    "PT027",
    "S101",  # TODO: remove
    "S301",  # TODO: remove
    "SIM117",
    "TD002",
    "TD003",
    "TRY003",  # TODO: maybe remove
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
    "prek>=0.3.6",
    "ruff>=0.16.5",
]
